version: 1.0.{build}
image: Visual Studio 2022
init:
- sh: cmake . -G"Visual Studio 17 2022"
build_script:
- cmd: >-
    echo "Testing..."

    cmake . -G"Visual Studio 17 2022"

    cmake --build .

    ctest -C "Debug" .
